# Generated by Django 5.2.7 on 2025-11-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('badminton', 'Badminton Court'), ('tennis', 'Tennis Court'), ('football', 'Football Field'), ('basketball', 'Basketball Court'), ('gym', 'Gym'), ('swimming', 'Swimming Pool'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=1, help_text='Number of players/capacity')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='facilities.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Availabilities',
                'ordering': ['facility', 'day_of_week', 'start_time'],
                'unique_together': {('facility', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
